# Generated by Django 4.2 on 2025-04-18 16:39

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=55)),
                ('number_of_room', models.PositiveIntegerField(default=0)),
                ('number_of_bathroom', models.PositiveIntegerField(default=0)),
                ('in_kitchen', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_of_room', models.PositiveIntegerField(default=0)),
                ('number_of_bath', models.PositiveIntegerField(default=0)),
                ('schedule', models.CharField(choices=[('ONE_OFF', 'ONE_OFF'), ('WEEKLY', 'WEEKLY'), ('BI_WEEKLY', 'BI_WEEKLY'), ('MONTHLY', 'MONTHLY')], default='ONE_OFF', max_length=20)),
                ('number_of_days', models.PositiveIntegerField(default=0)),
                ('selected_days', models.CharField(choices=[('MON', 'MONDAY'), ('TUE', 'TUESDAY'), ('WED', 'WEDNESDAY'), ('THU', 'THURSDAY'), ('FRI', 'FRIDAY'), ('SAT', 'SATURDAY'), ('SUN', 'SUNDAY')], max_length=20)),
                ('number_of_extras', models.PositiveIntegerField(default=0, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cleaning_location', models.TextField()),
                ('week_type', models.IntegerField(blank=True, choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')], null=True)),
                ('day_of_month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('weekdays', models.CharField(choices=[('MON', 'MONDAY'), ('TUE', 'TUESDAY'), ('WED', 'WEDNESDAY'), ('THU', 'THURSDAY'), ('FRI', 'FRIDAY'), ('SAT', 'SATURDAY'), ('SUN', 'SUNDAY')], max_length=12, null=True)),
                ('status', models.CharField(choices=[('NOT STARTED', 'NOT STARTED'), ('IN PROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED')], default='NOT STARTED', max_length=20)),
                ('payment_statement', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.CharField(max_length=15)),
                ('promo_code', models.CharField(blank=True, max_length=15)),
                ('discounted', models.BooleanField(default=False)),
                ('transation_id', models.CharField(max_length=15, unique=True)),
                ('status', models.CharField(default='pending', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=12, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('validity', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraSpace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=55)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.CharField(max_length=15)),
                ('transation_id', models.CharField(max_length=15, unique=True)),
                ('status', models.CharField(default='pending', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserKYCProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('id_image', models.ImageField(upload_to='ID image')),
                ('resume', models.FileField(upload_to='Resume')),
                ('id_document', models.FileField(upload_to='Resume')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
