# Generated by Django 4.2 on 2025-04-18 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkycprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payout',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.bookingdetail'),
        ),
        migrations.AddField(
            model_name='payout',
            name='cleaner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_cleaners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.bookingdetail'),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='cleaner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingpayment_cleaners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingpayment_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.apartmenttype'),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='cleaner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingdetail_cleanings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingdetail_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='extra_spaces',
            field=models.ManyToManyField(blank=True, to='service.extraspace'),
        ),
    ]
